In [1]:
import pandas as pd

df = pd.read_csv('data/flights_log.csv')
df.shape

(353, 14)

In [2]:
df.head()

,collected_at,route,flight_date,flight_status,dep_scheduled,dep_actual,dep_delay_min,arr_scheduled,arr_actual,arr_delay_min,calculated_dep_delay,calculated_arr_delay,flight_number,airline
0,2026-07-08T22:10:30.051593,BOM-FRA,2026-07-09,scheduled,2026-07-09T02:40:00+00:00,NaN,NaN,2026-07-09T08:05:00+00:00,NaN,20.0,NaN,NaN,NaN,Lufthansa
1,2026-07-08T22:10:30.051661,BOM-FRA,2026-07-08,landed,2026-07-08T11:40:00+00:00,2026-07-08T12:10:00+00:00,NaN,2026-07-08T17:55:00+00:00,2026-07-08T17:30:00+00:00,NaN,NaN,NaN,NaN,Lufthansa
2,2026-07-08T22:10:30.051677,BOM-FRA,2026-07-08,landed,2026-07-08T11:40:00+00:00,2026-07-08T12:10:00+00:00,NaN,2026-07-08T17:55:00+00:00,2026-07-08T17:30:00+00:00,NaN,NaN,NaN,NaN,Air India
3,2026-07-08T22:10:30.051687,BOM-FRA,2026-07-08,landed,2026-07-08T08:10:00+00:00,2026-07-08T08:34:00+00:00,9.0,2026-07-08T13:30:00+00:00,2026-07-08T13:39:00+00:00,9.0,NaN,NaN,NaN,DHL Air
4,2026-07-08T22:10:30.051696,BOM-FRA,2026-07-08,scheduled,2026-07-08T02:40:00+00:00,2026-07-08T04:08:00+00:00,74.0,2026-07-08T08:05:00+00:00,NaN,74.0,NaN,NaN,NaN,Air India

In [3]:
df['flight_status'].value_counts()

flight_status
landed       201
active        85
scheduled     67
Name: count, dtype: int64

In [4]:
landed_flights = df[df['flight_status'] == 'landed']
landed_flights['dep_delay_min'].describe()

count    58.000000
mean     16.000000
std       9.252785
min       1.000000
25%      11.000000
50%      15.000000
75%      20.000000
max      36.000000
Name: dep_delay_min, dtype: float64

In [5]:
landed_flights['dep_delay_min'].isna().sum()

np.int64(143)

In [6]:
landed_flights[['dep_scheduled', 'dep_actual', 'dep_delay_min']].head(10)

                dep_scheduled                 dep_actual  dep_delay_min
1   2026-07-08T11:40:00+00:00  2026-07-08T12:10:00+00:00            NaN
2   2026-07-08T11:40:00+00:00  2026-07-08T12:10:00+00:00            NaN
3   2026-07-08T08:10:00+00:00  2026-07-08T08:34:00+00:00            9.0
7   2026-07-07T08:20:00+00:00  2026-07-07T08:43:00+00:00           18.0
16  2026-07-08T09:38:00+00:00  2026-07-08T09:44:00+00:00            NaN
18  2026-07-08T00:50:00+00:00  2026-07-08T01:20:00+00:00            NaN
19  2026-07-08T00:50:00+00:00  2026-07-08T01:20:00+00:00            NaN
20  2026-07-08T00:50:00+00:00  2026-07-08T01:20:00+00:00            NaN
21  2026-07-07T12:10:00+00:00  2026-07-07T12:21:00+00:00            NaN
23  2026-07-07T12:10:00+00:00  2026-07-07T12:21:00+00:00            NaN

In [7]:
df['dep_scheduled'] = pd.to_datetime(df['dep_scheduled'])
df['dep_actual'] = pd.to_datetime(df['dep_actual'])

df['actual_delay_min'] = (df['dep_actual'] - df['dep_scheduled']).dt.total_seconds() / 60

In [8]:
df[['dep_scheduled', 'dep_actual', 'dep_delay_min', 'actual_delay_min']].head(10)

,dep_scheduled,dep_actual,dep_delay_min,actual_delay_min
0,2026-07-09 02:40:00+00:00,NaT,NaN,NaN
1,2026-07-08 11:40:00+00:00,2026-07-08 12:10:00+00:00,NaN,30.0
2,2026-07-08 11:40:00+00:00,2026-07-08 12:10:00+00:00,NaN,30.0
3,2026-07-08 08:10:00+00:00,2026-07-08 08:34:00+00:00,9.0,24.0
4,2026-07-08 02:40:00+00:00,2026-07-08 04:08:00+00:00,74.0,88.0
5,2026-07-08 02:40:00+00:00,2026-07-08 04:08:00+00:00,74.0,88.0
6,2026-07-08 02:40:00+00:00,2026-07-08 04:08:00+00:00,74.0,88.0
7,2026-07-07 08:20:00+00:00,2026-07-07 08:43:00+00:00,18.0,23.0
8,2026-07-07 08:20:00+00:00,NaT,NaN,NaN
9,2026-07-07 02:40:00+00:00,2026-07-07 03:22:00+00:00,41.0,42.0

In [9]:
df['arr_scheduled'] = pd.to_datetime(df['arr_scheduled'])
df['arr_actual'] = pd.to_datetime(df['arr_actual'])

df['actual_arr_delay_min'] = (df['arr_actual'] - df['arr_scheduled']).dt.total_seconds() / 60

In [10]:
df['actual_arr_delay_min'].notna().sum()

np.int64(201)

In [11]:
df['actual_delay_min'].notna().sum()

np.int64(312)

In [12]:
df.groupby('flight_status')['actual_delay_min'].apply(lambda x: x.notna().sum())

flight_status
active        69
landed       201
scheduled     42
Name: actual_delay_min, dtype: int64

In [13]:
df['has_departed'] = df['dep_actual'].notna()
df['has_arrived'] = df['arr_actual'].notna()

df[['flight_status', 'has_departed', 'has_arrived']].groupby('flight_status').sum()

               has_departed  has_arrived
flight_status
active                   69            0
landed                  201          201
scheduled                42            0

In [14]:
complete_flights = df[df['has_arrived'] == True]
complete_flights.shape

(201, 18)

In [15]:
df.groupby(['route', 'flight_date', 'airline']).size().sort_values(ascending=False).head(10)

route    flight_date  airline
BOM-FRA  2026-07-09   Lufthansa          7
         2026-07-08   Lufthansa          6
                      Air India          6
         2026-07-09   Air India          6
         2026-07-11   Air India          4
                      Lufthansa          4
         2026-07-12   Air India          4
                      Lufthansa          4
BLR-AMS  2026-07-09   KLM                4
                      Delta Air Lines    4
dtype: int64

In [16]:
import requests
import os
from dotenv import load_dotenv

load_dotenv()
API_KEY = os.getenv('AVIATIONSTACK_KEY')

response = requests.get('http://api.aviationstack.com/v1/flights', params={
    'access_key': API_KEY,
    'dep_iata': 'BOM',
    'arr_iata': 'FRA'
})
data = response.json()
data['data'][0]  # look at the full structure of one flight record

{'flight_date': '2026-07-18',
 'flight_status': 'active',
 'departure': {'airport': 'Chhatrapati Shivaji International (Sahar International)',
  'timezone': 'Asia/Kolkata',
  'iata': 'BOM',
  'icao': 'VABB',
  'terminal': '2',
  'gate': None,
  'delay': None,
  'scheduled': '2026-07-18T11:40:00+00:00',
  'estimated': '2026-07-18T11:40:00+00:00',
  'actual': '2026-07-18T11:56:00+00:00',
  'estimated_runway': '2026-07-18T11:56:00+00:00',
  'actual_runway': '2026-07-18T11:56:00+00:00'},
 'arrival': {'airport': 'Frankfurt International Airport',
  'timezone': 'Europe/Berlin',
  'iata': 'FRA',
  'icao': 'EDDF',
  'terminal': '1',
  'gate': None,
  'baggage': None,
  'scheduled': '2026-07-18T17:55:00+00:00',
  'delay': 17,
  'estimated': '2026-07-18T17:00:00+00:00',
  'actual': None,
  'estimated_runway': None,
  'actual_runway': None},
 'airline': {'name': 'Lufthansa', 'iata': 'LH', 'icao': 'DLH'},
 'flight': {'number': '7255',
  'iata': 'LH7255',
  'icao': 'DLH7255',
  'codeshared': {'airline_name': 'air india',
   'airline_iata': 'ai',
   'airline_icao': 'aic',
   'flight_number': '2027',
   'flight_iata': 'ai2027',
   'flight_icao': 'aic2027'}},
 'aircraft': {'registration': None,
  'iata': None,
  'icao': None,
  'icao24': '8013C3'},
 'live': None}

In [17]:
data['data'][0]['flight']

{'number': '7255',
 'iata': 'LH7255',
 'icao': 'DLH7255',
 'codeshared': {'airline_name': 'air india',
  'airline_iata': 'ai',
  'airline_icao': 'aic',
  'flight_number': '2027',
  'flight_iata': 'ai2027',
  'flight_icao': 'aic2027'}}

In [18]:
df.groupby(['route', 'flight_date', 'flight_number']).size().sort_values(ascending=False).head(10)

route    flight_date  flight_number
BLR-AMS  2026-07-16   KL880            3
DEL-CDG  2026-07-16   AF283            3
BLR-AMS  2026-07-12   DL9478           2
         2026-07-14   DL9478           2
                      AF3126           2
         2026-07-12   AF3126           2
         2026-07-15   AF3126           2
                      DL9478           2
                      KL880            2
         2026-07-14   KL880            2
dtype: int64

In [19]:
df = pd.read_csv('data/flights_log.csv')
df.columns.tolist()

['collected_at',
 'route',
 'flight_date',
 'flight_status',
 'dep_scheduled',
 'dep_actual',
 'dep_delay_min',
 'arr_scheduled',
 'arr_actual',
 'arr_delay_min',
 'calculated_dep_delay',
 'calculated_arr_delay',
 'flight_number',
 'airline']

In [20]:
import csv

CSV_FILE = 'data/flights_log.csv'
EXPECTED_COLUMNS = 14

fixed_rows = []
with open(CSV_FILE, 'r', newline='') as f:
    reader = csv.reader(f)
    header = next(reader)
    fixed_rows.append(header)
    
    for row in reader:
        if len(row) < EXPECTED_COLUMNS:
            # Old rows are missing the 3 newest columns (calculated_dep_delay,
            # calculated_arr_delay, flight_number) which sit right before 'airline'.
            # Pad with empty values, keeping airline (last field) in its place.
            missing_count = EXPECTED_COLUMNS - len(row)
            airline = row[-1]
            row = row[:-1] + [''] * missing_count + [airline]
        fixed_rows.append(row)

with open(CSV_FILE, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(fixed_rows)

print(f'Fixed {len(fixed_rows)-1} rows to have {EXPECTED_COLUMNS} columns each.')

Fixed 353 rows to have 14 columns each.

In [21]:
df = pd.read_csv('data/flights_log.csv')
df.shape

(353, 14)

In [22]:
df['dep_scheduled'] = pd.to_datetime(df['dep_scheduled'])
df['dep_actual'] = pd.to_datetime(df['dep_actual'])
df['arr_scheduled'] = pd.to_datetime(df['arr_scheduled'])
df['arr_actual'] = pd.to_datetime(df['arr_actual'])

df['actual_delay_min'] = (df['dep_actual'] - df['dep_scheduled']).dt.total_seconds() / 60
df['actual_arr_delay_min'] = (df['arr_actual'] - df['arr_scheduled']).dt.total_seconds() / 60

In [23]:
import csv

CSV_FILE = 'data/flights_log.csv'
EXPECTED_COLUMNS = 14

fixed_rows = []
with open(CSV_FILE, 'r', newline='') as f:
    reader = csv.reader(f)
    header = next(reader)
    fixed_rows.append(header)
    
    for row in reader:
        if len(row) < EXPECTED_COLUMNS:
            missing_count = EXPECTED_COLUMNS - len(row)
            airline = row[-1]
            row = row[:-1] + [''] * missing_count + [airline]
        fixed_rows.append(row)

with open(CSV_FILE, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(fixed_rows)

print(f'Fixed {len(fixed_rows)-1} rows to have {EXPECTED_COLUMNS} columns each.')

Fixed 353 rows to have 14 columns each.

In [24]:
df = pd.read_csv('data/flights_log.csv')
df.shape

(353, 14)

In [25]:
df.shape

(353, 14)

In [26]:
df['dep_scheduled'] = pd.to_datetime(df['dep_scheduled'])
df['dep_actual'] = pd.to_datetime(df['dep_actual'])
df['arr_scheduled'] = pd.to_datetime(df['arr_scheduled'])
df['arr_actual'] = pd.to_datetime(df['arr_actual'])

df['has_departed'] = df['dep_actual'].notna()
df['has_arrived'] = df['arr_actual'].notna()

df['has_arrived'].sum()

np.int64(201)

In [27]:
complete_flights = df[df['has_arrived'] == True].copy()

complete_flights['actual_delay_min'] = (complete_flights['dep_actual'] - complete_flights['dep_scheduled']).dt.total_seconds() / 60
complete_flights['actual_arr_delay_min'] = (complete_flights['arr_actual'] - complete_flights['arr_scheduled']).dt.total_seconds() / 60

complete_flights[['route', 'flight_date', 'airline', 'actual_delay_min', 'actual_arr_delay_min']].head()

,route,flight_date,airline,actual_delay_min,actual_arr_delay_min
1,BOM-FRA,2026-07-08,Lufthansa,30.0,-25.0
2,BOM-FRA,2026-07-08,Air India,30.0,-25.0
3,BOM-FRA,2026-07-08,DHL Air,24.0,9.0
7,BOM-FRA,2026-07-07,Lufthansa Cargo,23.0,18.0
16,DEL-CDG,2026-07-08,FedEx,6.0,-23.0

In [28]:
complete_flights.groupby('route')['actual_arr_delay_min'].agg(['mean', 'median', 'count']).sort_values('mean', ascending=False)

              mean  median  count
route
BOM-FRA   1.955882     7.0     68
DEL-CDG -11.800000   -10.0     90
BLR-AMS -18.651163   -19.0     43

In [29]:
complete_flights['is_delayed'] = complete_flights['actual_arr_delay_min'] >= 15

complete_flights.groupby('route')['is_delayed'].agg(['mean', 'sum', 'count'])

             mean  sum  count
route
BLR-AMS  0.000000    0     43
BOM-FRA  0.382353   26     68
DEL-CDG  0.088889    8     90

In [30]:
bom_fra = complete_flights[complete_flights['route'] == 'BOM-FRA']
bom_fra.groupby('airline')['is_delayed'].agg(['mean', 'sum', 'count']).sort_values('mean', ascending=False)

                     mean  sum  count
airline
Alitalia         0.625000    5      8
Air Canada       0.545455    6     11
Lufthansa Cargo  0.500000    1      2
Air India        0.300000    6     20
Lufthansa        0.300000    6     20
DHL Air          0.285714    2      7

In [31]:
complete_flights = df[df['has_arrived'] == True].copy()
complete_flights['actual_arr_delay_min'] = (complete_flights['arr_actual'] - complete_flights['arr_scheduled']).dt.total_seconds() / 60
complete_flights['is_delayed'] = complete_flights['actual_arr_delay_min'] >= 15
complete_flights.shape

(201, 18)

In [32]:
bom_fra = complete_flights[complete_flights['route'] == 'BOM-FRA'].copy()

bom_fra['day_of_week'] = bom_fra['dep_scheduled'].dt.day_name()
bom_fra['dep_hour'] = bom_fra['dep_scheduled'].dt.hour

bom_fra.groupby('day_of_week')['is_delayed'].agg(['mean', 'sum', 'count'])

                 mean  sum  count
day_of_week
Friday       1.000000    3      3
Monday       0.000000    0      9
Saturday     0.400000    4     10
Sunday       0.000000    0      7
Thursday     0.333333    4     12
Tuesday      0.833333    5      6
Wednesday    0.476190   10     21

In [33]:
bom_fra.groupby('dep_hour')['is_delayed'].agg(['mean', 'sum', 'count']).sort_values('dep_hour')

              mean  sum  count
dep_hour
2         0.560976   23     41
8         0.333333    3      9
11        0.000000    0     18

In [34]:
sample = complete_flights[complete_flights['route'] == 'BOM-FRA'].iloc[0]
print(sample[['dep_scheduled', 'dep_actual', 'arr_scheduled', 'arr_actual']])

dep_scheduled    2026-07-08 11:40:00+00:00
dep_actual       2026-07-08 12:10:00+00:00
arr_scheduled    2026-07-08 17:55:00+00:00
arr_actual       2026-07-08 17:30:00+00:00
Name: 1, dtype: object

In [35]:
df.shape
complete_flights = df[df['has_arrived'] == True]
complete_flights.shape

(201, 16)

In [36]:
df.shape

(353, 16)