In [2]:
import pandas as pd

df = pd.read_csv('data/flights_log.csv')
df.shape

(465, 14)

In [3]:
df.head()

,collected_at,route,flight_date,flight_status,dep_scheduled,dep_actual,dep_delay_min,arr_scheduled,arr_actual,arr_delay_min,calculated_dep_delay,calculated_arr_delay,flight_number,airline
0,2026-07-08T22:10:30.051593,BOM-FRA,2026-07-09,scheduled,2026-07-09T02:40:00+00:00,NaN,NaN,2026-07-09T08:05:00+00:00,NaN,20.0,NaN,NaN,NaN,Lufthansa
1,2026-07-08T22:10:30.051661,BOM-FRA,2026-07-08,landed,2026-07-08T11:40:00+00:00,2026-07-08T12:10:00+00:00,NaN,2026-07-08T17:55:00+00:00,2026-07-08T17:30:00+00:00,NaN,NaN,NaN,NaN,Lufthansa
2,2026-07-08T22:10:30.051677,BOM-FRA,2026-07-08,landed,2026-07-08T11:40:00+00:00,2026-07-08T12:10:00+00:00,NaN,2026-07-08T17:55:00+00:00,2026-07-08T17:30:00+00:00,NaN,NaN,NaN,NaN,Air India
3,2026-07-08T22:10:30.051687,BOM-FRA,2026-07-08,landed,2026-07-08T08:10:00+00:00,2026-07-08T08:34:00+00:00,9.0,2026-07-08T13:30:00+00:00,2026-07-08T13:39:00+00:00,9.0,NaN,NaN,NaN,DHL Air
4,2026-07-08T22:10:30.051696,BOM-FRA,2026-07-08,scheduled,2026-07-08T02:40:00+00:00,2026-07-08T04:08:00+00:00,74.0,2026-07-08T08:05:00+00:00,NaN,74.0,NaN,NaN,NaN,Air India

In [4]:
df['flight_status'].value_counts()

flight_status
landed       260
active       129
scheduled     76
Name: count, dtype: int64

In [5]:
landed_flights = df[df['flight_status'] == 'landed']
landed_flights['dep_delay_min'].describe()

count    84.000000
mean     14.821429
std      11.754682
min       1.000000
25%       5.000000
50%      14.500000
75%      20.000000
max      45.000000
Name: dep_delay_min, dtype: float64

In [6]:
landed_flights['dep_delay_min'].isna().sum()

np.int64(176)

In [7]:
landed_flights[['dep_scheduled', 'dep_actual', 'dep_delay_min']].head(10)

                dep_scheduled                 dep_actual  dep_delay_min
1   2026-07-08T11:40:00+00:00  2026-07-08T12:10:00+00:00            NaN
2   2026-07-08T11:40:00+00:00  2026-07-08T12:10:00+00:00            NaN
3   2026-07-08T08:10:00+00:00  2026-07-08T08:34:00+00:00            9.0
7   2026-07-07T08:20:00+00:00  2026-07-07T08:43:00+00:00           18.0
16  2026-07-08T09:38:00+00:00  2026-07-08T09:44:00+00:00            NaN
18  2026-07-08T00:50:00+00:00  2026-07-08T01:20:00+00:00            NaN
19  2026-07-08T00:50:00+00:00  2026-07-08T01:20:00+00:00            NaN
20  2026-07-08T00:50:00+00:00  2026-07-08T01:20:00+00:00            NaN
21  2026-07-07T12:10:00+00:00  2026-07-07T12:21:00+00:00            NaN
23  2026-07-07T12:10:00+00:00  2026-07-07T12:21:00+00:00            NaN

In [8]:
df['dep_scheduled'] = pd.to_datetime(df['dep_scheduled'])
df['dep_actual'] = pd.to_datetime(df['dep_actual'])

df['actual_delay_min'] = (df['dep_actual'] - df['dep_scheduled']).dt.total_seconds() / 60

In [9]:
df[['dep_scheduled', 'dep_actual', 'dep_delay_min', 'actual_delay_min']].head(10)

,dep_scheduled,dep_actual,dep_delay_min,actual_delay_min
0,2026-07-09 02:40:00+00:00,NaT,NaN,NaN
1,2026-07-08 11:40:00+00:00,2026-07-08 12:10:00+00:00,NaN,30.0
2,2026-07-08 11:40:00+00:00,2026-07-08 12:10:00+00:00,NaN,30.0
3,2026-07-08 08:10:00+00:00,2026-07-08 08:34:00+00:00,9.0,24.0
4,2026-07-08 02:40:00+00:00,2026-07-08 04:08:00+00:00,74.0,88.0
5,2026-07-08 02:40:00+00:00,2026-07-08 04:08:00+00:00,74.0,88.0
6,2026-07-08 02:40:00+00:00,2026-07-08 04:08:00+00:00,74.0,88.0
7,2026-07-07 08:20:00+00:00,2026-07-07 08:43:00+00:00,18.0,23.0
8,2026-07-07 08:20:00+00:00,NaT,NaN,NaN
9,2026-07-07 02:40:00+00:00,2026-07-07 03:22:00+00:00,41.0,42.0

In [10]:
df['arr_scheduled'] = pd.to_datetime(df['arr_scheduled'])
df['arr_actual'] = pd.to_datetime(df['arr_actual'])

df['actual_arr_delay_min'] = (df['arr_actual'] - df['arr_scheduled']).dt.total_seconds() / 60

In [11]:
df['actual_arr_delay_min'].notna().sum()

np.int64(260)

In [12]:
df['actual_delay_min'].notna().sum()

np.int64(405)

In [13]:
df.groupby('flight_status')['actual_delay_min'].apply(lambda x: x.notna().sum())

flight_status
active        99
landed       260
scheduled     46
Name: actual_delay_min, dtype: int64

In [14]:
df['has_departed'] = df['dep_actual'].notna()
df['has_arrived'] = df['arr_actual'].notna()

df[['flight_status', 'has_departed', 'has_arrived']].groupby('flight_status').sum()

               has_departed  has_arrived
flight_status
active                   99            0
landed                  260          260
scheduled                46            0

In [15]:
complete_flights = df[df['has_arrived'] == True]
complete_flights.shape

(260, 18)

In [16]:
df.groupby(['route', 'flight_date', 'airline']).size().sort_values(ascending=False).head(10)

route    flight_date  airline
BOM-FRA  2026-07-09   Lufthansa          7
         2026-07-08   Lufthansa          6
         2026-07-09   Air India          6
         2026-07-08   Air India          6
BLR-AMS  2026-07-09   Delta Air Lines    4
                      Air France         4
BOM-FRA  2026-07-11   Lufthansa          4
         2026-07-12   Air India          4
         2026-07-11   Air India          4
         2026-07-12   Lufthansa          4
dtype: int64

In [17]:
import requests
import os
from dotenv import load_dotenv

load_dotenv()
API_KEY = os.getenv('AVIATIONSTACK_KEY')

response = requests.get('http://api.aviationstack.com/v1/flights', params={
    'access_key': API_KEY,
    'dep_iata': 'BOM',
    'arr_iata': 'FRA'
})
data = response.json()
data['data'][0]  # look at the full structure of one flight record

{'flight_date': '2026-07-22',
 'flight_status': 'active',
 'departure': {'airport': 'Chhatrapati Shivaji International (Sahar International)',
  'timezone': 'Asia/Kolkata',
  'iata': 'BOM',
  'icao': 'VABB',
  'terminal': '2',
  'gate': None,
  'delay': None,
  'scheduled': '2026-07-22T11:40:00+00:00',
  'estimated': '2026-07-22T11:40:00+00:00',
  'actual': None,
  'estimated_runway': None,
  'actual_runway': None},
 'arrival': {'airport': 'Frankfurt International Airport',
  'timezone': 'Europe/Berlin',
  'iata': 'FRA',
  'icao': 'EDDF',
  'terminal': '1',
  'gate': None,
  'baggage': None,
  'scheduled': '2026-07-22T17:55:00+00:00',
  'delay': 10,
  'estimated': None,
  'actual': None,
  'estimated_runway': None,
  'actual_runway': None},
 'airline': {'name': 'Lufthansa', 'iata': 'LH', 'icao': 'DLH'},
 'flight': {'number': '7255',
  'iata': 'LH7255',
  'icao': 'DLH7255',
  'codeshared': {'airline_name': 'air india',
   'airline_iata': 'ai',
   'airline_icao': 'aic',
   'flight_number': '2027',
   'flight_iata': 'ai2027',
   'flight_icao': 'aic2027'}},
 'aircraft': {'registration': None,
  'iata': None,
  'icao': None,
  'icao24': '8013C2'},
 'live': None}

In [18]:
data['data'][0]['flight']

{'number': '7255',
 'iata': 'LH7255',
 'icao': 'DLH7255',
 'codeshared': {'airline_name': 'air india',
  'airline_iata': 'ai',
  'airline_icao': 'aic',
  'flight_number': '2027',
  'flight_iata': 'ai2027',
  'flight_icao': 'aic2027'}}

In [19]:
df.groupby(['route', 'flight_date', 'flight_number']).size().sort_values(ascending=False).head(10)

route    flight_date  flight_number
BLR-AMS  2026-07-16   KL880            3
DEL-CDG  2026-07-16   AF283            3
BLR-AMS  2026-07-12   DL9478           2
         2026-07-11   SQ7352           2
         2026-07-14   AF3126           2
         2026-07-15   AF3126           2
         2026-07-14   DL9478           2
         2026-07-12   KL880            2
         2026-07-16   SQ7352           2
         2026-07-17   AF3126           2
dtype: int64

In [20]:
df = pd.read_csv('data/flights_log.csv')
df.columns.tolist()

['collected_at',
 'route',
 'flight_date',
 'flight_status',
 'dep_scheduled',
 'dep_actual',
 'dep_delay_min',
 'arr_scheduled',
 'arr_actual',
 'arr_delay_min',
 'calculated_dep_delay',
 'calculated_arr_delay',
 'flight_number',
 'airline']

In [21]:
import csv

CSV_FILE = 'data/flights_log.csv'
EXPECTED_COLUMNS = 14

fixed_rows = []
with open(CSV_FILE, 'r', newline='') as f:
    reader = csv.reader(f)
    header = next(reader)
    fixed_rows.append(header)
    
    for row in reader:
        if len(row) < EXPECTED_COLUMNS:
            # Old rows are missing the 3 newest columns (calculated_dep_delay,
            # calculated_arr_delay, flight_number) which sit right before 'airline'.
            # Pad with empty values, keeping airline (last field) in its place.
            missing_count = EXPECTED_COLUMNS - len(row)
            airline = row[-1]
            row = row[:-1] + [''] * missing_count + [airline]
        fixed_rows.append(row)

with open(CSV_FILE, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(fixed_rows)

print(f'Fixed {len(fixed_rows)-1} rows to have {EXPECTED_COLUMNS} columns each.')

Fixed 465 rows to have 14 columns each.

In [22]:
df = pd.read_csv('data/flights_log.csv')
df.shape

(465, 14)

In [23]:
df['dep_scheduled'] = pd.to_datetime(df['dep_scheduled'])
df['dep_actual'] = pd.to_datetime(df['dep_actual'])
df['arr_scheduled'] = pd.to_datetime(df['arr_scheduled'])
df['arr_actual'] = pd.to_datetime(df['arr_actual'])

df['actual_delay_min'] = (df['dep_actual'] - df['dep_scheduled']).dt.total_seconds() / 60
df['actual_arr_delay_min'] = (df['arr_actual'] - df['arr_scheduled']).dt.total_seconds() / 60

In [24]:
import csv

CSV_FILE = 'data/flights_log.csv'
EXPECTED_COLUMNS = 14

fixed_rows = []
with open(CSV_FILE, 'r', newline='') as f:
    reader = csv.reader(f)
    header = next(reader)
    fixed_rows.append(header)
    
    for row in reader:
        if len(row) < EXPECTED_COLUMNS:
            missing_count = EXPECTED_COLUMNS - len(row)
            airline = row[-1]
            row = row[:-1] + [''] * missing_count + [airline]
        fixed_rows.append(row)

with open(CSV_FILE, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(fixed_rows)

print(f'Fixed {len(fixed_rows)-1} rows to have {EXPECTED_COLUMNS} columns each.')

Fixed 465 rows to have 14 columns each.

In [25]:
df = pd.read_csv('data/flights_log.csv')
df.shape

(465, 14)

In [26]:
df.shape

(465, 14)

In [27]:
df['dep_scheduled'] = pd.to_datetime(df['dep_scheduled'])
df['dep_actual'] = pd.to_datetime(df['dep_actual'])
df['arr_scheduled'] = pd.to_datetime(df['arr_scheduled'])
df['arr_actual'] = pd.to_datetime(df['arr_actual'])

df['has_departed'] = df['dep_actual'].notna()
df['has_arrived'] = df['arr_actual'].notna()

df['has_arrived'].sum()

np.int64(260)

In [28]:
complete_flights = df[df['has_arrived'] == True].copy()

complete_flights['actual_delay_min'] = (complete_flights['dep_actual'] - complete_flights['dep_scheduled']).dt.total_seconds() / 60
complete_flights['actual_arr_delay_min'] = (complete_flights['arr_actual'] - complete_flights['arr_scheduled']).dt.total_seconds() / 60

complete_flights[['route', 'flight_date', 'airline', 'actual_delay_min', 'actual_arr_delay_min']].head()

,route,flight_date,airline,actual_delay_min,actual_arr_delay_min
1,BOM-FRA,2026-07-08,Lufthansa,30.0,-25.0
2,BOM-FRA,2026-07-08,Air India,30.0,-25.0
3,BOM-FRA,2026-07-08,DHL Air,24.0,9.0
7,BOM-FRA,2026-07-07,Lufthansa Cargo,23.0,18.0
16,DEL-CDG,2026-07-08,FedEx,6.0,-23.0

In [29]:
complete_flights.groupby('route')['actual_arr_delay_min'].agg(['mean', 'median', 'count']).sort_values('mean', ascending=False)

              mean  median  count
route
BOM-FRA   0.505618     5.0     89
DEL-CDG -11.975207   -10.0    121
BLR-AMS -18.320000   -18.0     50

In [30]:
complete_flights['is_delayed'] = complete_flights['actual_arr_delay_min'] >= 15

complete_flights.groupby('route')['is_delayed'].agg(['mean', 'sum', 'count'])

             mean  sum  count
route
BLR-AMS  0.000000    0     50
BOM-FRA  0.359551   32     89
DEL-CDG  0.066116    8    121

In [31]:
bom_fra = complete_flights[complete_flights['route'] == 'BOM-FRA']
bom_fra.groupby('airline')['is_delayed'].agg(['mean', 'sum', 'count']).sort_values('mean', ascending=False)

                     mean  sum  count
airline
Lufthansa Cargo  0.666667    2      3
Alitalia         0.600000    6     10
Air Canada       0.500000    7     14
DHL Air          0.375000    3      8
Air India        0.269231    7     26
Lufthansa        0.259259    7     27
AeroLogic        0.000000    0      1

In [32]:
complete_flights = df[df['has_arrived'] == True].copy()
complete_flights['actual_arr_delay_min'] = (complete_flights['arr_actual'] - complete_flights['arr_scheduled']).dt.total_seconds() / 60
complete_flights['is_delayed'] = complete_flights['actual_arr_delay_min'] >= 15
complete_flights.shape

(260, 18)

In [33]:
bom_fra = complete_flights[complete_flights['route'] == 'BOM-FRA'].copy()

bom_fra['day_of_week'] = bom_fra['dep_scheduled'].dt.day_name()
bom_fra['dep_hour'] = bom_fra['dep_scheduled'].dt.hour

bom_fra.groupby('day_of_week')['is_delayed'].agg(['mean', 'sum', 'count'])

                 mean  sum  count
day_of_week
Friday       1.000000    3      3
Monday       0.066667    1     15
Saturday     0.500000    8     16
Sunday       0.000000    0     14
Thursday     0.333333    4     12
Tuesday      0.750000    6      8
Wednesday    0.476190   10     21

In [34]:
bom_fra.groupby('dep_hour')['is_delayed'].agg(['mean', 'sum', 'count']).sort_values('dep_hour')

              mean  sum  count
dep_hour
2         0.509434   27     53
8         0.416667    5     12
11        0.000000    0     24

In [35]:
sample = complete_flights[complete_flights['route'] == 'BOM-FRA'].iloc[0]
print(sample[['dep_scheduled', 'dep_actual', 'arr_scheduled', 'arr_actual']])

dep_scheduled    2026-07-08 11:40:00+00:00
dep_actual       2026-07-08 12:10:00+00:00
arr_scheduled    2026-07-08 17:55:00+00:00
arr_actual       2026-07-08 17:30:00+00:00
Name: 1, dtype: object

In [36]:
df.shape
complete_flights = df[df['has_arrived'] == True]
complete_flights.shape

(260, 16)

In [37]:
df.shape

(465, 16)

In [38]:
complete_flights.groupby('route').size()

route
BLR-AMS     50
BOM-FRA     89
DEL-CDG    121
dtype: int64

In [39]:
complete_flights['dep_hour'] = complete_flights['dep_scheduled'].dt.hour
complete_flights['day_of_week'] = complete_flights['dep_scheduled'].dt.day_name()
complete_flights['is_weekend'] = complete_flights['dep_scheduled'].dt.dayofweek >= 5

features = pd.get_dummies(complete_flights[['route', 'airline', 'dep_hour', 'day_of_week', 'is_weekend']], columns=['route', 'airline', 'day_of_week'])
features.head()

,dep_hour,is_weekend,route_BLR-AMS,route_BOM-FRA,route_DEL-CDG,airline_AeroLogic,airline_Air Canada,airline_Air France,airline_Air India,airline_Alitalia,...,airline_Lufthansa,airline_Lufthansa Cargo,airline_Singapore Airlines,day_of_week_Friday,day_of_week_Monday,day_of_week_Saturday,day_of_week_Sunday,day_of_week_Thursday,day_of_week_Tuesday,day_of_week_Wednesday
1,11,False,False,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,True
2,11,False,False,True,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
3,8,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
7,8,False,False,True,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
16,9,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [40]:
complete_flights['airline'].value_counts()

airline
KLM                   43
Delta Air Lines       42
Air France            42
Air India             39
Lufthansa             27
Singapore Airlines    17
Air Canada            14
FedEx                 12
Alitalia              10
DHL Air                8
Lufthansa Cargo        3
Cathay Pacific         2
AeroLogic              1
Name: count, dtype: int64

In [41]:
airline_counts = complete_flights['airline'].value_counts()
rare_airlines = airline_counts[airline_counts < 10].index

complete_flights['airline_grouped'] = complete_flights['airline'].apply(
    lambda x: 'Other' if x in rare_airlines else x
)

complete_flights['airline_grouped'].value_counts()

airline_grouped
KLM                   43
Delta Air Lines       42
Air France            42
Air India             39
Lufthansa             27
Singapore Airlines    17
Other                 14
Air Canada            14
FedEx                 12
Alitalia              10
Name: count, dtype: int64

In [42]:
features = pd.get_dummies(
    complete_flights[['route', 'airline_grouped', 'dep_hour', 'day_of_week', 'is_weekend']],
    columns=['route', 'airline_grouped', 'day_of_week']
)
features.shape

(260, 22)

In [43]:
df = pd.read_csv('data/flights_log.csv')

df['dep_scheduled'] = pd.to_datetime(df['dep_scheduled'])
df['dep_actual'] = pd.to_datetime(df['dep_actual'])
df['arr_scheduled'] = pd.to_datetime(df['arr_scheduled'])
df['arr_actual'] = pd.to_datetime(df['arr_actual'])

df['has_arrived'] = df['arr_actual'].notna()

complete_flights = df[df['has_arrived'] == True].copy()

complete_flights['actual_arr_delay_min'] = (complete_flights['arr_actual'] - complete_flights['arr_scheduled']).dt.total_seconds() / 60
complete_flights['is_delayed'] = complete_flights['actual_arr_delay_min'] >= 15

complete_flights['is_delayed'].value_counts()

is_delayed
False    220
True      40
Name: count, dtype: int64

In [44]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

X = features
y = complete_flights['is_delayed']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(X_train.shape, X_test.shape)

(208, 22) (52, 22)

In [45]:
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.93      0.93      0.93        44
        True       0.62      0.62      0.62         8

    accuracy                           0.88        52
   macro avg       0.78      0.78      0.78        52
weighted avg       0.88      0.88      0.88        52

In [46]:
model_balanced = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced')
model_balanced.fit(X_train, y_train)
y_pred_balanced = model_balanced.predict(X_test)

print(classification_report(y_test, y_pred_balanced))
print(confusion_matrix(y_test, y_pred_balanced))

              precision    recall  f1-score   support

       False       0.97      0.89      0.93        44
        True       0.58      0.88      0.70         8

    accuracy                           0.88        52
   macro avg       0.78      0.88      0.81        52
weighted avg       0.91      0.88      0.89        52

[[39  5]
 [ 1  7]]

In [47]:
import pandas as pd

coefficients = pd.DataFrame({
    'feature': X.columns,
    'coefficient': model_balanced.coef_[0]
}).sort_values('coefficient', ascending=False)

coefficients

                               feature  coefficient
13               airline_grouped_Other     2.392294
3                        route_BOM-FRA     2.139075
21               day_of_week_Wednesday     1.611477
17                day_of_week_Saturday     0.895978
8             airline_grouped_Alitalia     0.676199
5           airline_grouped_Air Canada     0.241579
20                 day_of_week_Tuesday     0.182510
15                  day_of_week_Friday     0.097564
19                day_of_week_Thursday     0.013401
14  airline_grouped_Singapore Airlines    -0.040144
7            airline_grouped_Air India    -0.064910
12           airline_grouped_Lufthansa    -0.170446
10               airline_grouped_FedEx    -0.181739
4                        route_DEL-CDG    -0.319430
0                             dep_hour    -0.431477
1                           is_weekend    -0.682546
6           airline_grouped_Air France    -0.886622
9      airline_grouped_Delta Air Lines    -0.934430
11                 airline_grouped_KLM    -1.023090
16                  day_of_week_Monday    -1.213714
18                  day_of_week_Sunday    -1.578524
2                        route_BLR-AMS    -1.810953

In [48]:
complete_flights['day_of_week'] = complete_flights['dep_scheduled'].dt.day_name()

saturday_by_route = complete_flights.groupby(['route', 'day_of_week'])['is_delayed'].agg(['mean', 'count']).reset_index()
saturday_by_route[saturday_by_route['day_of_week'] == 'Saturday']

      route day_of_week  mean  count
1   BLR-AMS    Saturday   0.0      2
8   BOM-FRA    Saturday   0.5     16
15  DEL-CDG    Saturday   0.0     11

In [49]:
airline_counts = complete_flights['airline'].value_counts()
rare_airlines = airline_counts[airline_counts < 10].index

complete_flights['airline_grouped'] = complete_flights['airline'].apply(
    lambda x: 'Other' if x in rare_airlines else x
)

complete_flights['dep_hour'] = complete_flights['dep_scheduled'].dt.hour
complete_flights['day_of_week'] = complete_flights['dep_scheduled'].dt.day_name()
complete_flights['is_weekend'] = complete_flights['dep_scheduled'].dt.dayofweek >= 5

features = pd.get_dummies(
    complete_flights[['route', 'airline_grouped', 'dep_hour', 'day_of_week', 'is_weekend']],
    columns=['route', 'airline_grouped', 'day_of_week']
)
features.shape

(260, 22)

In [50]:
X = features
y = complete_flights['is_delayed']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

model_balanced = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced')
model_balanced.fit(X_train, y_train)
y_pred_balanced = model_balanced.predict(X_test)

print(classification_report(y_test, y_pred_balanced))
print(confusion_matrix(y_test, y_pred_balanced))

              precision    recall  f1-score   support

       False       0.97      0.89      0.93        44
        True       0.58      0.88      0.70         8

    accuracy                           0.88        52
   macro avg       0.78      0.88      0.81        52
weighted avg       0.91      0.88      0.89        52

[[39  5]
 [ 1  7]]

In [51]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print(classification_report(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))

              precision    recall  f1-score   support

       False       0.97      0.89      0.93        44
        True       0.58      0.88      0.70         8

    accuracy                           0.88        52
   macro avg       0.78      0.88      0.81        52
weighted avg       0.91      0.88      0.89        52

[[39  5]
 [ 1  7]]